coupon_image:
  type: upload
  default: ""
  description: Upload an image to display at the top of the modal.
coupon_image_width:
  type: string
  default: "150px"
  description: The uploaded image width. You can use px, % etc, e.g. 100% will add a full modal width (minus padding) image.
coupon_secondary_title_color:
  type: string
  default: "var(--primary)"
  description: The “big text” appears below the image. You can set the color of the text.
coupon_description_color:
  type: string
  default: "var(--primary)"
  description: The “little text” appears below the big text. You can set the color of the text.
coupon_background_color:
  type: string
  default: "var(--secondary)"
  description: Change the modal background color.
coupon_link_color:
  type: string
  default: "var(--primary-medium)"
  description: Change the footer link color. This applies if the use gate buttons setting is disabled and you have set up a custom gate.  
coupon_links:
  description: "Coupon Links"
  default: >-
  json_schema: '
  {
    "type": "array",
    "format": "table",
    "uniqueItems": true,
    "items": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number",
          "minLength": 1
        },
        "title": {
          "type": "string",
          "minLength": 1
        },       
        "subtitle": {
          "type": "string",
          "minLength": 1
        },
        "text": {
          "type": "string",
          "minLength": 1
        },
        "class": {
          "type": "string",
          "minLength": 1
        }      
      },
      "additionalProperties": false
    }
  }'
